# Generated by Django 3.2.9 on 2021-11-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
